services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: home-intranet-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - home-intranet-nginx

networks:
  home-intranet-nginx:
    external: true
